# docker-compose.yml (Swarm Version - Level 3)

services:
  # 1. NGINX (API Gateway)
  nginx:
    image: nginx:latest # Sử dụng image build sẵn
    ports:
      # Chỉ cổng này được mở ra máy thật
      - "80:80" 
    volumes:
      # Map file config vào container
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: # Chỉ định thứ tự khởi động (Swarm có thể không tuân thủ nghiêm ngặt)
      - student-service
      - client
      - grade-service
    networks:
      - student-net
    deploy: # Cấu hình cho Swarm
      replicas: 1 # Chạy 1 bản sao Nginx

  # 2. STUDENT-SERVICE (Backend 1)
  student-service:
    # Image sẽ được build thủ công hoặc từ registry
    # Tên image thường là: <tên_thư_mục_gốc>-<tên_service>:latest
    image: student-management-student-service:latest 
    build: ./student-service # Giữ lại build context để build thủ công
    networks:
      - student-net
    depends_on:
      - db
      - rabbitmq
    environment:
      - DB_URL=mongodb://db:27017/studentdb
      - JWT_SECRET=my_super_secret_key_123 # Nên dùng secret của Swarm
    deploy:
      replicas: 2 # Chạy 2 bản sao

  # 3. GRADE-SERVICE (Backend 2)
  grade-service:
    image: student-management-grade-service:latest
    build: ./grade-service
    networks:
      - student-net
    depends_on:
      - db
      - rabbitmq
    environment:
      - DB_URL=mongodb://db:27017/gradedb
    deploy:
      replicas: 1 # Chạy 1 bản sao
      restart_policy: # Tự khởi động lại nếu lỗi
        condition: on-failure

  # 4. CLIENT (Frontend - Production Nginx)
  client:
    image: student-management-client:latest
    build: ./client # Sẽ dùng Dockerfile production mới
    networks:
      - student-net
    # Xóa bỏ: ports, stdin_open, tty, volumes
    deploy:
      replicas: 1

  # 5. DB (MongoDB)
  db:
    image: mongo:latest # Image build sẵn
    networks:
      - student-net
    volumes:
      - mongo-data:/data/db # Giữ volume data
    deploy:
      replicas: 1
      # Có thể thêm placement constraint để DB luôn chạy trên 1 node cụ thể

  # 6. RABBITMQ
  rabbitmq:
    image: rabbitmq:3-management # Image build sẵn
    ports:
      - "15672:15672" # Giữ cổng quản lý
    networks:
      - student-net
    deploy:
      replicas: 1

  # 7. NOTIFICATION-SERVICE
  notification-service:
    image: student-management-notification-service:latest
    build: ./notification-service
    networks:
      - student-net
    depends_on:
      - rabbitmq
    env_file: # Vẫn đọc file .env
      - ./notification-service/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

# Định nghĩa mạng overlay cho Swarm
networks:
  student-net:
    driver: overlay # Phải là overlay
    attachable: true # Cho phép kết nối tạm thời để debug

# Định nghĩa volume cho MongoDB
volumes:
  mongo-data: